export const SESSION_POLICY_ABI = [{
  type: "function",
  name: "revoke",
  stateMutability: "nonpayable",
  inputs: [{ name: "digest", type: "bytes32" }],
  outputs: [],
}] as const;

export const EXIT_HANDLER_ABI = [{
  type: "function",
  name: "registerRule",
  stateMutability: "nonpayable",
  inputs: [
    { name: "pool", type: "address" },
    { name: "exitKind", type: "uint8" },
    { name: "trigger", type: "uint8" },
    { name: "oneCollateral", type: "uint256" },
    { name: "triggerPrice", type: "uint256" },
    { name: "minimumBestLevelQuantity", type: "uint256" },
    { name: "quantity", type: "uint256" },
    { name: "expireTimestampNs", type: "uint64" },
    { name: "collateral", type: "address" },
    { name: "outcomeToken", type: "address" },
    { name: "outcomeTokenId", type: "uint256" },
    {
      name: "grant",
      type: "tuple",
      components: [
        { name: "owner", type: "address" },
        { name: "executor", type: "address" },
        { name: "marketId", type: "bytes32" },
        { name: "pool", type: "address" },
        { name: "collateral", type: "address" },
        { name: "outcomeToken", type: "address" },
        { name: "outcomeTokenId", type: "uint256" },
        { name: "oneCollateral", type: "uint256" },
        { name: "outcome", type: "uint8" },
        { name: "side", type: "uint8" },
        { name: "maxContracts", type: "uint256" },
        { name: "issuedAt", type: "uint64" },
        { name: "expiresAt", type: "uint64" },
        { name: "nonce", type: "uint256" },
      ],
    },
    { name: "signature", type: "bytes" },
  ],
  outputs: [{ name: "ruleId", type: "bytes32" }],
}, {
  type: "event",
  name: "RuleRegistered",
  inputs: [
    { name: "ruleId", type: "bytes32", indexed: true },
    { name: "owner", type: "address", indexed: true },
    { name: "pool", type: "address", indexed: true },
    { name: "exitKind", type: "uint8", indexed: false },
    { name: "trigger", type: "uint8", indexed: false },
    { name: "quantity", type: "uint256", indexed: false },
  ],
}] as const;
